# .github/workflows/daily_email.yml

# A descriptive name for your scheduled task
name: Send Daily CurioMail Email

# This section defines the schedule
on:
  schedule:
    # This is a cron expression that means "at 1:30 AM UTC every day"
    # 1:30 AM UTC is 7:00 AM in your time zone (IST)
    - cron: '30 1 * * *'
  # This line allows you to also run it manually from the GitHub Actions tab
  workflow_dispatch:

# This section defines the actual job to be done
jobs:
  send-email-job:
    # Use the latest version of an Ubuntu Linux virtual machine
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Use a modern Python version

      # Step 3: Install all the necessary libraries from your requirements file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run your main Python script
      - name: Run main.py email script
        # This is where you provide your secrets to the script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          FROM_ADDR: ${{ secrets.FROM_ADDR }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py